/* Only history actually flown. No future simulation, reward or permanent storage. */
(function(root){'use strict';const O=root.Orbital;let recording=null,active=null;const memory=new Map(),key=()=>O.App.currentId+':'+O.App.profile.difficulty;
function snapshot(s){return {...s,cargo:s.cargo.slice(),teleports:[],cargoBodies:s.cargoBodies.map(c=>({...c,trail:[]})),branchProgress:structuredClone(s.branchProgress||{}),dropEvents:(s.dropEvents||[]).map(x=>({...x}))};}
function start(s){active=null;recording={key:key(),angle:s.launchAngle,speed:s.launchSpeed,frames:[snapshot(s)],resets:[]};}
function observe(a,b,l){if(!recording)return;if(a.flybyAngle>0&&b.flybyAngle===0&&a.flybyIndex===b.flybyIndex){const v=O.Routes.view(l,a),leg=v.flybys?.[a.flybyIndex];if(leg)recording.resets.push({t:b.t,planet:l.planets[leg.planet].name,degrees:O.Physics.deg(a.flybyAngle),goal:leg.degrees});}if(recording.frames.length<2400&&(b.t-recording.frames.at(-1).t>=.05||b.status!=='flying'))recording.frames.push(snapshot(b));}
function finish(s,points,level){const d=recording||{key:key(),angle:s.launchAngle,speed:s.launchSpeed,frames:[],resets:[]};if(d.frames.at(-1)?.t!==s.t)d.frames.push(snapshot(s));d.points=points.map(p=>({...p}));d.final=snapshot(s);d.level=level;const prev=memory.get(key())||[];memory.delete(key());memory.set(key(),[...prev,d].slice(-2));while(memory.size>4)memory.delete(memory.keys().next().value);recording=null;active={data:d,index:d.frames.length-1,compare:false};}
function prior(){return active?(memory.get(active.data.key)||[]).at(-2):null;}function clearView(){active=null;recording=null;}function selectTime(t){if(!active)return;let a=0,b=active.data.frames.length-1;while(a<b){let m=Math.ceil((a+b)/2);if(active.data.frames[m].t<=t)a=m;else b=m-1;}active.index=a;}function setCompare(){if(active)active.compare=!active.compare;}
function renderModel(){if(!active)return null;const s=active.data.frames[active.index];return{state:s,trail:active.data.points.filter(p=>(p.t||0)<=s.t),ghost:active.compare?prior()?.points:null};}
function diagnosis(l,s){if(!s)return '';if(s.status==='won')return `${s.branchId?'Ветвь '+s.branchId+'. ':''}Доставка: ${s.flybyIndex} облётов, ${s.portalIndex} переходов${l.stops?.length?', '+s.dropIndex+' промежуточных адреса':''}.`;const reasons={planet:'Столкновение с планетой',asteroid:'Столкновение с астероидом',boundary:'Выход за границу карты',timeout:'Истёк срок рейса',manifest:'Недостаточно обязательного груза',branch:'Не закончена допустимая ветвь',deliveries:'Не обслужены все получатели','drop-speed':'Слишком высокая скорость передачи посылки',fuel:'Превышен физический предел старта',overspeed:'Превышена скорость стыковки',window:'Встреча вне окна приёма',portals:'Не завершены переходы',gates:'Не пройдены кольца',flybys:'Не завершены облёты'};let result=`${reasons[s.reason]||'Рейс не завершён'}. Момент ${s.t.toFixed(2)} с.`,v=O.Routes.view(l,s),leg=v.flybys?.[s.flybyIndex],last=active?.data.resets.at(-1);if(leg)result+=` Выполнено ${s.flybyIndex} / ${v.flybys.length} облётов. ${last?`Последний сброс: ${last.planet}, ${Math.floor(last.degrees)}° из ${last.goal}° на ${last.t.toFixed(2)} с.`:`Цель: ${l.planets[leg.planet].name}, ${Math.floor(O.Physics.deg(s.flybyAngle))}° / ${leg.degrees}°.`}`;return result;}
O.Review={start,observe,finish,prior,clearView,selectTime,setCompare,renderModel,diagnosis,get active(){return active;}};
})(typeof globalThis!=='undefined'?globalThis:window);
