/* Explicit, nonredundant goals. Archived medals never impersonate current proof. */
(function(root){'use strict';const O=root.Orbital=root.Orbital||{},R=O.Routes||(typeof require==='function'?require('./routes.js'):null);
const rules=l=>l.medalRules||[{type:'delivery'},{type:'economy',limit:l.parSpeed},{type:'cargo'}];
function meets(rule,l,s,r={}){if(!s||s.status!=='won')return false;switch(rule.type){case'delivery':return true;case'economy':return s.launchSpeed*(s.stats?.fuelFactor||1)<=rule.limit+1e-8;case'cargo':return R.collected(l,s)===R.cargoIds(l,s).length;case'precision':return s.dockPrecision+1e-8>=rule.limit;case'time':return s.t<=rule.limit+1e-8;case'branches':return new Set([...(r.routes||[]),s.branchId].filter(Boolean)).size>=(l.branches?.length||2);default:return false;}}
function mask(l,s,r={}){return rules(l).reduce((m,x,i)=>m|(meets(x,l,s,r)?1<<i:0),0);}
function describe(l,s,speed,r={},training=false,stats={}){const v=s?.launchSpeed??speed,f=s?.stats?.fuelFactor||stats.fuelFactor||1,got=R.collected(l,s),count=R.cargoIds(l,s).length,view=R.view(l,s),run=mask(l,s,r),won=s?.status==='won',failed=s&&s.status!=='won'&&s.status!=='flying';const all=(view.flybys?.length||0)+(view.gates?.length||0)+(view.portalOrder?.length||0)+(l.stops?.length||0),done=(s?.flybyIndex||0)+(s?.gateIndex||0)+(s?.portalIndex||0)+(s?.dropIndex||0);
return rules(l).map((rule,i)=>{let title,condition,detail,progress=0,ready=false;switch(rule.type){case'delivery':title='Доставка';condition='Закрой обязательный маршрут и все адреса';detail=won?'Капсула доставлена':`Этапы ${done} / ${all}`;progress=won?1:done/(all+1);break;case'economy':title='Бережный импульс';condition=`Расчётный расход ≤ ${rule.limit}, затем доставка`;detail=`${(v*f).toFixed(1)} / ${rule.limit}`;ready=v*f<=rule.limit;progress=ready?1:0;break;case'cargo':title=l.stops?.length?'Дополнительный груз':'Полный груз';condition=`Доставь ${count} свободных контейнера за один рейс`;detail=`На борту ${got} / ${count}`;progress=got/Math.max(1,count);ready=got===count;break;case'precision':title='Точный заход';condition=`Точность стыковки ≥ ${Math.round(rule.limit*100)}%`;detail=s?.dockPrecision?`${Math.round(s.dockPrecision*100)} / ${Math.round(rule.limit*100)}%`:`Цель ${Math.round(rule.limit*100)}%`;progress=s?.dockPrecision||0;break;case'time':title='В срок';condition=`Доставка за ${rule.limit} с или быстрее`;detail=`${(s?.t||0).toFixed(1)} / ${rule.limit} с`;progress=Math.min(1,(s?.t||0)/rule.limit);break;case'branches':title='Исследователь';condition='Закрой обе ветви в разных успешных рейсах';let n=new Set([...(r.routes||[]),...(won&&s?.branchId?[s.branchId]:[])]).size;detail=`Маршруты ${n} / ${l.branches.length}`;progress=n/l.branches.length;ready=n===l.branches.length;}
const bit=1<<i,earned=!!(r.currentMedals&bit),archive=!earned&&!!(r.legacyMedals&bit),state=training?'training':won?(run&bit?'won':'missed'):failed?'failed':ready?'ready':'pending';return{bit,key:['delivery','economy','cargo'][i],title,condition,detail,progress,earned,archive,state,status:training?'Тренировка · без наград':won?(run&bit?'Получена':'Условие не выполнено'):failed?'Рейс не завершён':ready?'Нужна доставка':'Цель рейса'};});}
O.Medals={mask,describe,rules,meets};if(typeof module!=='undefined'&&module.exports)module.exports=O.Medals;
})(typeof globalThis!=='undefined'?globalThis:window);
