'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const Pagination = require('../pdf-pagination');
const entries = [];
const section = Pagination.heading(' Раздел  один ', 0, entries);
const subsection = Pagination.heading('Подраздел', 2, entries);
assert.equal(entries[0].text, 'Раздел один');
assert.notEqual(section.id, subsection.id);
const line = node => ({ type: 'line', item: { _node: node } });
const pages = [{ items: [] }, { items: [line(section)] }, { items: [line(subsection)] }, { items: [line(subsection)] }];
const locations = Pagination.locate(pages, entries);
assert.deepEqual(locations, { [section.id]: 1, [subsection.id]: 2 }, 'a wrapping heading belongs to its first page');
assert.throws(() => Pagination.locate([{ items: [] }], entries), /определить страницы/);
assert.doesNotThrow(() => Pagination.verify(locations, { ...locations }));
assert.throws(() => Pagination.verify(locations, { ...locations, [section.id]: 3 }), /изменились/);
const toc = Pagination.contents(entries, locations, false);
assert.equal(toc.stack[0].text, 'Содержание');
assert.equal(toc.pageBreak, 'after');
assert.deepEqual(toc.stack[1].table.body.map(row => row[1].text), ['1', '2']);
assert.equal(toc.stack[1].table.body[1][0].margin[0], 24);
assert.equal(toc.stack[1].table.body[0][0].linkToDestination, section.id);
assert.equal(Pagination.contents(entries, null, true).stack[0].text, 'Contents');
for (let page = 1; page <= 20; page++) assert.equal(Pagination.footer(page).columns[1].text, String(page - 1));
const layout = { paddingLeft: () => 3 };
const source = { content: [section], layout };
const copy = Pagination.copy(source);
copy.content[0].text = 'Changed';
assert.equal(source.content[0].text, 'Раздел один', 'layout passes must not reuse mutated nodes');
assert.equal(copy.layout.paddingLeft(), 3, 'layout functions survive cloning');
const exporter = fs.readFileSync(require('node:path').join(__dirname, '..', 'pdf-download.js'), 'utf8');
assert.doesNotMatch(exporter, /fillColor:/, 'exported note blocks have no background fill');
assert.match(exporter, /pagination\.verify/);
console.log('PDF pagination: actual section pages, page zero, serial footers, contents links and independent layout passes passed');
