'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const Frames = require('../pdf-block-frames');
const style = Frames.style, margins = [39.69, 42.52, 39.69, 51.02];
const page = () => ({ pageSize: { width: 595.28, height: 841.89 }, items: [] });
const pages = [page(), page(), page()];
function mark(index, frame, edge, x, y) {
    const marker = Frames.marker(frame, edge).canvas[0];
    pages[index].items.push({ type: 'vector', item: { ...marker, x1: x, y1: y } });
}
const outer = { id: 'outer', width: 515.9, depth: 0 };
mark(0, outer, 'start', 39.69 + style.paddingX, 80 + style.paddingY);
mark(0, outer, 'rowEnd', 39.69 + style.paddingX, 300);
pages[0].items.push({ type: 'svg', item: { y: 300, _height: 50, pdfFrameOwners: ['outer'] } });
mark(2, outer, 'start', 39.69 + style.paddingX, margins[1] + style.paddingY);
mark(2, outer, 'end', 39.69 + style.paddingX, 340 - style.paddingY);
const inner = { id: 'inner', width: 493.2, depth: 1 };
mark(2, inner, 'start', 39.69 + 2 * style.paddingX, 110 + style.paddingY);
mark(2, inner, 'end', 39.69 + 2 * style.paddingX, 200 - style.paddingY);
const frames = Frames.collect(pages, margins);
assert.equal(frames.length, 4);
assert.equal(frames[0].y, 80);
assert.equal(frames[0].height, 350 + style.paddingY - 80, 'continuation frames must include the last paragraph even if its row-end marker moved to the next page');
assert.equal(frames[1].y, margins[1]);
assert.equal(frames[2].height, 340 - margins[1]);
assert.equal(frames[3].depth, 1);
const calls = [];
const pdf = {};
for (const name of ['switchToPage', 'save', 'fillColor', 'rect', 'path', 'fill', 'lineWidth', 'strokeColor', 'roundedRect', 'stroke', 'lineCap', 'moveTo', 'lineTo', 'restore']) pdf[name] = (...args) => { calls.push([name, ...args]); return pdf; };
Frames.draw(pdf, frames);
assert.equal(calls.filter(call => call[0] === 'roundedRect').length, 4);
assert.equal(calls.filter(call => call[0] === 'path').length, 16);
assert.equal(calls.filter(call => call[0] === 'lineWidth' && call[1] === style.stripe).length, 4);
assert.ok(style.stripe > style.border * 2);
const css = fs.readFileSync(require('node:path').join(__dirname, '..', 'styles/print.css'), 'utf8');
assert.match(css, /border-radius: 1\.8mm/);
assert.match(css, /border-left: 0\.65mm solid #8c939e/);
assert.match(css, /--print-surface: #f6f7f9/);
assert.match(css, /--print-surface-nested: #fbfbfc/);
mark(0, { id: 'broken', width: 600, depth: 0 }, 'start', 39.69 + style.paddingX, 90);
mark(0, { id: 'broken', width: 600, depth: 0 }, 'end', 39.69 + style.paddingX, 190);
assert.throws(() => Frames.collect(pages, margins), /поля страницы/);
console.log('PDF frames: print styling, nested and multi-page borders, rounding and margins passed');
