'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Publication = require('../constructor/publication');
const root = path.join(__dirname, '..');
const pipeline = fs.readFileSync(path.join(root, 'tools/ci.js'), 'utf8');
assert.ok(pipeline.indexOf('BuildSite.build({ root, output })') < pipeline.indexOf('Tests.run(root, { site: output })'), 'JSON-only publication must be rebuilt before canonical artifact checks');
assert.match(fs.readFileSync(path.join(root, 'tests/canonical-notes.test.js'), 'utf8'), /ALMANION_TEST_SITE/, 'canonical checks must verify the actual deployable artifact');
(async () => {
    const values = new Map(), storage = { getItem: key => values.get(key), setItem: (key, value) => values.set(key, value) };
    const expected = { id: 'test', content: 'new' };
    let deployed = { id: 'test', content: 'old' }, failure = true;
    const tracker = Publication.create({ owner: 'fixture', storage, fetch: async url => ({ ok: true, json: async () => url.startsWith('https://api.github.com/') ? { workflow_runs: [{ name: 'Deploy GitHub Pages', status: 'completed', conclusion: failure ? 'failure' : 'success', html_url: 'https://github.com/Almanion/almanion.github.io/actions/runs/123' }] } : deployed }) });
    await tracker.track('likbez', 'test', 'fixture-sha', expected);
    const record = tracker.get('likbez', 'test');
    record.acceptedAt -= 6 * 60 * 1000;
    await tracker.retry('likbez', 'test');
    assert.equal(record.stage, 'failed');
    assert.match(record.error, /сборка/);
    assert.match(record.deploymentUrl, /actions\/runs/);
    failure = false; record.deploymentCheckedAt = 0;
    await tracker.retry('likbez', 'test');
    assert.equal(record.stage, 'delayed', 'a delayed deployment cannot masquerade as an endlessly running update');
    deployed = expected;
    await tracker.retry('likbez', 'test');
    assert.equal(record.stage, 'live', 'a later successful rebuild resolves the original accepted publication');
    tracker.stop();
    console.log('publication: JSON-first pipeline, failed deployment, bounded status and recovery passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
