'use strict';const fs=require('fs'),assert=require('assert'),path=require('path');require('../src/levels.js');const O=globalThis.Orbital,P=require('../src/physics.js'),R=require('../src/routes.js'),E=require('../src/economy.js'),G=require('../src/progression.js'),M=require('../src/medals.js'),C=require('../src/cosmetics.js'),L=O.LEVELS;let n=0;const check=(v,m)=>{n++;assert.ok(v,m);};const eq=(a,b,m)=>{n++;assert.deepStrictEqual(a,b,m);};
const start=Date.now(),report={};const worlds=l=>JSON.stringify([l.start,l.planets,l.target,l.portals,l.cargo]);
check(L.length===80&&O.SECTORS.length===20,'campaign size');check(G.achievements.length===93,'93 achievements');check(new Set(G.achievements.map(a=>a.id)).size===93,'unique achievements');check(C.TRAILS.length===11&&G.SKINS.length===10,'late cosmetics');
const profile=G.fresh(),flights=[],newIds=[20,21,22,23,...Array.from({length:12},(_,i)=>68+i)];let freezes=0;
for(const l of L){check(G.unlocked(profile,l.id),'sequential unlock '+l.id);const geometry=worlds(l),courses=l.solutions||[l.solution];for(const c of courses){for(const mode of ['normal','pro']){let course=l.solutions?c:mode==='pro'?(l.proSolution||c):c;const prepared=P.prepareLevel(l,mode),s=P.simulate(prepared,course.angle,course.speed).state;check(s.status==='won',`won ${l.id+1}/${mode}/${c.branch} ${s.reason}`);check(R.collected(l,s)===3,'three intended cargo');check(!c.branch||s.branchId===c.branch,'actual branch');check(s.flybyIndex===(R.view(l,s).flybys||[]).length,'all loops');check(s.portalIndex===(R.view(l,s).portalOrder||[]).length,'all portals');const before=JSON.stringify(profile),training=G.complete(G.sanitize(profile),l,{...s,assisted:true});eq(training.totalCredits,0,'training credits');eq(before,JSON.stringify(profile),'training no mutation of input');const result=G.complete(profile,l,s);check(result.totalCredits>=0,'nonnegative payout');const money=profile.credits,xp=profile.xp,data=profile.data,repeat=G.complete(profile,l,s);eq([repeat.totalCredits,repeat.totalXP,repeat.data],[0,0,0],'repeat no resources');eq([profile.credits,profile.xp,profile.data],[money,xp,data],'repeat no farm');flights.push({id:l.id,mode,branch:c.branch||null,s,course});}}
 check(G.record(profile,l.id).currentMedals===7,'three distinct medals reachable '+(l.id+1));eq(worlds(l),geometry,'world unchanged by branch');
 if(l.branches){check(l.branches.length===2,'two routes');check(l.branches[0].flybys[0].direction!==l.branches[1].flybys[0].direction,'opposite first loops');for(const b of l.branches){const pts=b.manifest.map(i=>l.cargo[i]);const area=Math.abs((pts[1].x-pts[0].x)*(pts[2].y-pts[0].y)-(pts[1].y-pts[0].y)*(pts[2].x-pts[0].x));check(area>1000,'noncollinear distinct cargo');check(b.flybys.every(f=>f.degrees>180),'real turns not straight');}}
 if(newIds.includes(l.id)){for(const c of courses){/* Explicit fixed-step rerun at DT/2. */let h=P.createState(P.prepareLevel(l),c.angle,c.speed);for(let i=0;h.status==='flying'&&i<40000;i++)h=P.step(h,P.prepareLevel(l),P.DT/2);check(h.status==='won','half step '+l.id);for(let tier=1;tier<=5;tier++){const pr=G.fresh();for(const k in pr.upgrades)pr.upgrades[k]=tier;for(const mode of ['normal','pro']){const s=P.simulate(P.prepareLevel(l,mode),c.angle,c.speed,G.stats(pr)).state;check(s.status==='won'&&R.collected(l,s)===3,'upgraded '+l.id+'/'+tier+'/'+mode);}}
 if(l.dynamic){const frozen=structuredClone(l);for(const p of frozen.planets)delete p.motion;const s=P.simulate(P.prepareLevel(frozen),c.angle,c.speed).state;if(s.status!=='won')freezes++;}}
 }
}
report.flights=flights.length;report.motionCounterfactualFailures=freezes;report.profileBeforeEngineering={credits:profile.credits,data:profile.data,xp:profile.xp,achievements:profile.achievements.length};check(G.completed(profile)===80,'complete campaign');check(Object.values(profile.records).every(r=>r.currentMedals===7),'all goals');check(profile.credits<=25+L.reduce((n,l)=>n+E.capReward(l),0),'finite budget');
// Valid purchased equipment, normal receipts, no resource injection.
for(const k of Object.keys(profile.upgrades))check(G.buy(profile,k).ok,'buy '+k);for(let i=1;i<4;i++){check(G.buy(profile,'scanner').ok,'scanner IV');check(G.buy(profile,'docking').ok,'dock IV');}check(G.buy(profile,'scanner').ok,'scanner V');check(profile.credits>=0,'no fabricated resources');
for(const l of L){const c=l.solutions?.[0]||l.proSolution||l.solution;let s=P.simulate(P.prepareLevel(l,'pro'),c.angle,c.speed,G.stats(profile)).state;check(s.status==='won','magnet replay '+l.id);G.complete(profile,l,s);}
// Search already authored neighbourhood for high-quality actual docking, not fake records.
let precision=Object.values(profile.records).filter(r=>r.bestPrecision>=.95).length;for(const l of L){if(precision>=40)break;if(G.record(profile,l.id).bestPrecision>=.95)continue;const c=l.solutions?.[0]||l.proSolution||l.solution;let found=false;for(const dv of [0,-1,1,-2,2]){for(const da of [0,-.1,.1,-.2,.2,-.3,.3,-.5,.5]){const s=P.simulate(P.prepareLevel(l,'pro'),c.angle+da,c.speed+dv,G.stats(profile)).state;if(s.status==='won'&&s.dockPrecision>=.95){G.complete(profile,l,s);precision++;found=true;break;}}if(found)break;}}
profile.flags.export=true;G.awardAchievements(profile);const cash=profile.credits+G.invested(profile),data=profile.data+G.dataInvested(profile);G.respec(profile);eq(profile.credits,cash,'refund exact');eq(profile.data,data,'refund research exact');const snap=JSON.stringify(profile);G.respec(profile);eq(JSON.stringify(profile),snap,'repeat refund no farm');
report.achievementsMissing=G.achievements.filter(a=>!profile.achievements.includes(a.id)).map(a=>({id:a.id,progress:a.progress(profile),target:a.target}));report.finalCampaign={xp:profile.xp,credits:profile.credits,data:profile.data,achievements:profile.achievements.length,precision};fs.writeFileSync(path.join(__dirname,'../docs/completed-v8-profile.json'),JSON.stringify(profile));
// Fresh and migrated storage semantics.
const saved=G.sanitize(profile);eq(saved.credits,profile.credits,'roundtrip credits');eq(saved.data,profile.data,'roundtrip data');eq(saved.xp,profile.xp,'roundtrip XP');eq(saved.records,profile.records,'roundtrip records');const old=structuredClone(profile);old.version=7;for(const k of Object.keys(old.records))if(+k>=68)delete old.records[k];old.data=Object.values(old.records).reduce((n,r)=>n+r.dataPaid,0);const migrated=G.sanitize(old);eq(migrated.credits,old.credits,'v7 cash preserved');eq(migrated.data,old.data,'v7 research preserved');check(Object.values(migrated.records).every(r=>r.currentMedals===0&&r.legacyMedals===r.medals),'archive not current');check(migrated.achievements.every(a=>old.achievements.includes(a)),'no silent new achievement grant');
const inherited=G.sanitize({...old,upgrades:{scanner:2,magnet:1,docking:0,engine:0},receipts:[]});G.respec(inherited);eq(inherited.upgrades,{scanner:2,magnet:1,docking:0,engine:0},'inherited modules retained');
for(const l of L){const zero=G.stats(G.fresh()),full={...zero,dockingLevel:5,capture:42};check(P.captureRadius(P.prepareLevel(l,'pro'),full)>P.captureRadius(P.prepareLevel(l,'pro'),zero),'dock useful '+l.id);}
const f=flights[0];const rat0=E.rating(L[0],f.s),rat5=E.rating(L[0],{...f.s,stats:{...f.s.stats,fuelFactor:.85}});check(rat5.parts.fuel>rat0.parts.fuel,'engine economic value at same actual speed');check(C.TRAILS.filter(t=>C.unlocked(G.fresh(),t)).length===1,'one fresh trail');check(C.TRAILS.every(t=>C.unlocked(profile,t)),'late cosmetic attainable');

for(const f of flights){for(const jump of f.s.teleports){eq(jump.before,jump.after,'portal conserves both velocity components');check(jump.t>=0&&jump.t<=f.s.t,'portal timestamp');}if(L[f.id].stops){eq(f.s.dropEvents.map(d=>d.id),L[f.id].stops.map(d=>d.id),'ordered addresses');check(f.s.dropEvents.every(d=>Math.hypot(d.vx,d.vy)>1),'no stop at recipients');}}
const plain={id:0,start:{x:100,y:100},target:{x:1000,y:100},planets:[],rocks:[],cargo:[],timeLimit:20,parSpeed:200,rules:{minCargo:0}};
const ship0=P.simulate(plain,0,150).state,ship1=P.simulate({...plain,stops:[{id:'D1',name:'One',x:300,y:100,r:20},{id:'D2',name:'Two',x:650,y:100,r:20}]},0,150).state;
check(ship0.status==='won'&&ship1.status==='won','synthetic delivery');check(Math.abs(ship1.vx-ship0.vx)<1e-10&&Math.abs(ship1.t-ship0.t)<1e-8,'no impulse or time jump at stops');eq(ship1.dropIndex,2,'two recipients exactly once');
for(const l of L.filter(l=>l.stops)){const noCargo=structuredClone(l);noCargo.cargo=[];const q=P.simulate(P.prepareLevel(noCargo),l.solution.angle,l.solution.speed).state;check(q.status==='won','free cargo not mandatory for address delivery');}
report.assertions=n;report.runtimeSeconds=(Date.now()-start)/1000;report.status='passed';fs.writeFileSync(path.join(__dirname,'../docs/core-results-v8.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.achievementsMissing.length)process.exitCode=2;
