'use strict';const fs=require('fs'),path=require('path'),P=require('../src/physics.js'),R=require('../src/routes.js');const root=path.resolve(__dirname,'..');
const offsets=[[0,0],[-.1,0],[.1,0],[-.2,0],[.2,0],[0,-1],[0,1],[-.1,-1],[-.1,1],[.1,-1],[.1,1]];
function trace(l,c,dt=P.DT,stats={}){let s=P.createState(l,c.angle,c.speed,stats),arr=[s];for(let i=0;s.status==='flying'&&i<15000;i++){s=P.step(s,l,dt);arr.push(s);}return{state:s,trace:arr};}
const nearest=(a,t)=>a.reduce((x,p)=>Math.abs(p.t-t)<Math.abs(x.t-t)?p:x,a[0]);const xy=p=>({x:p.x,y:p.y});
function spread(p){let dist=Infinity;for(let i=0;i<3;i++)for(let j=0;j<i;j++)dist=Math.min(dist,Math.hypot(p[i].x-p[j].x,p[i].y-p[j].y));return{dist,alt:Math.abs((p[1].x-p[0].x)*(p[2].y-p[0].y)-(p[1].y-p[0].y)*(p[2].x-p[0].x))/Math.max(...p.map((q,i)=>Math.hypot(q.x-p[(i+1)%3].x,q.y-p[(i+1)%3].y)))}}
const names=[['Две дуги Элары','Полярная развилка','Перекрёсток миров','Дальняя альтернатива'],['Развилка приливов','Два пути к Нерею','Каскад четырёх миров','Возвратная развилка'],['Согласование орбит','Двойная топология','Перекрёстный резонанс','Пять горизонтов'],['Почта обсерваторий','Четыре адреса','Дрейфующий получатель','Последняя миля']];
const starts=[20,68,72,76];
function candidate(seed,family,index){const id=starts[family]+index,multi=family===3;
 const l={id,sector:family===0?5:17+family-1,newIn:8,routeRevision:8,name:names[family][index],subtitle:multi?'Несколько адресов · один запуск':'Две физические ветви на общей карте',brief:multi?'Передай адресные посылки промежуточным станциям и заверши рейс на финальной. Три свободных контейнера — дополнительная задача.':'Выбери направление первого облёта. Обе ветви существуют на одной карте: первая отправляется по часовой стрелке, вторая — обратно.',start:seed.start,planets:seed.planets.map((p,i)=>({...p,name:['Элара','Тирса','Нерей','Кассия'][i],tint:['#81d9dc','#ffc68e','#bea7ff','#7db8ee'][i],ring:i===2})),target:seed.target,rocks:[],cargo:[],gates:[],flybys:[],portalOrder:[],portals:[],branches:[],timeLimit:Math.ceil(Math.max(seed.a.path.at(-1)[4],seed.b?.path.at(-1)[4]||0)+8),parSpeed:Math.max(seed.a.speed,seed.b?.speed||0)+6,qualityTime:Math.max(seed.a.path.at(-1)[4],seed.b?.path.at(-1)[4]||0)*1.16,initialAngle:Math.min(179,seed.a.angle+7),initialSpeed:Math.max(60,seed.a.speed-5),dynamic:family>0,expert:family>0,maneuver:true,motionKind:multi?'multidrop':'branch',rules:{captureCap:family===0?24:19,proCaptureCap:family===0?19:14,proGateScale:.94,minCargo:0},solution:{angle:seed.a.angle,speed:seed.a.speed},proSolution:{angle:seed.a.angle,speed:seed.a.speed},solutions:[]};
 if(multi){l.sector=19;if(index===3){let q=l.target;l.target={...q,motion:{cx:q.x,cy:q.y,rx:9,ry:7,period:30,phase:0,direction:1}};const end=seed.a.path.at(-1);let t=end[4],m=l.target.motion;m.cx=q.x-m.rx*Math.cos(2*Math.PI*t/m.period);m.cy=q.y-m.ry*Math.sin(2*Math.PI*t/m.period);Object.assign(l.target,xy(P.bodyAt(l.target,0)));}}
 const inputs=multi?[seed.a]:[seed.a,seed.b];
 for(let j=0;j<inputs.length;j++){const raw=inputs[j],bid=j?'B':'A';const b={id:bid,name:j?'Обратный каскад':'Прямой каскад',flybys:raw.events.map(e=>({planet:e.body,direction:e.sweep>0?1:-1,degrees:family===0?185+index*3:family===2?222+index*2:208+index*2,radius:e.radius})),gates:[],portalOrder:[],manifest:[],minCargo:0,parSpeed:raw.speed+6,qualityTime:raw.path.at(-1)[4]*1.16};
 raw.portals.forEach((p,k)=>{let pid=bid+(k+1);l.portals.push({id:pid,branch:bid,afterFlybys:k+1,afterPortals:k,entrance:p.entrance,exit:p.exit,color:j?'#eab7ff':'#75e8ed'});b.portalOrder.push(pid);});l.branches.push(b);l.solutions.push({branch:bid,angle:raw.angle,speed:raw.speed});}
 const runs=l.solutions.map(c=>trace(P.prepareLevel(l),c));if(runs.some((r,j)=>r.state.status!=='won'||r.state.branchId!==l.branches[j].id))return null;
 for(let j=0;j<inputs.length;j++){const raw=inputs[j],arr=runs[j].trace,b=l.branches[j];b.gates=raw.events.map(e=>({...xy(nearest(arr,e.from+(e.to-e.from)*.37)),r:family===0?34:30}));let ts;if(raw.events.length===1){let e=raw.events[0];ts=[.22,.48,.75].map(v=>e.from+(e.to-e.from)*v);}else if(raw.events.length===2){let e=raw.events[0],f=raw.events[1];ts=[.3,.7].map(v=>e.from+(e.to-e.from)*v).concat(f.from+(f.to-f.from)*.55);}else{let ix=[0,Math.floor(raw.events.length/2)],last=raw.events.length-1;while(last>0&&ix.some(k=>raw.events[k].body===raw.events[last].body))last--;ix.push(last);ts=ix.map(i=>{let e=raw.events[i];return e.from+(e.to-e.from)*.53;});}const p=ts.map(t=>xy(nearest(arr,t))),sp=spread(p);if(sp.dist<(family===0?40:110)||sp.alt<(family===0?30:85))return null;p.forEach((q,k)=>{b.manifest.push(l.cargo.length);l.cargo.push({...q,branch:b.id,label:b.id+(k+1)});});b.minCargo=3;}
 if(multi){const b=l.branches[0],raw=seed.a,arr=runs[0].trace;l.flybys=b.flybys;l.gates=b.gates;l.portalOrder=b.portalOrder;l.portals=l.portals.map(p=>{let q={...p};delete q.branch;return q;});delete l.branches;l.solutions[0]={...l.solution};l.cargo=l.cargo.map(c=>{let q={...c};delete q.branch;return q;});l.stops=[];l.payload=['Обсерватория','Ретранслятор','Архив'];for(let k=0;k<(index===0?2:3);k++){const e=raw.events[k],sample=nearest(arr,e.to-.16);let stop={id:'D'+(k+1),name:l.payload[k],...xy(sample),r:23,afterFlybys:k+1,afterPortals:k,maxSpeed:Math.ceil(Math.hypot(sample.vx,sample.vy)+45)};if(index>=2&&k===1){const m={cx:stop.x,cy:stop.y,rx:10,ry:8,period:25,phase:.4,direction:1},a=m.phase+2*Math.PI*sample.t/m.period;m.cx-=m.rx*Math.cos(a);m.cy-=m.ry*Math.sin(a);stop.motion=m;Object.assign(stop,xy(P.bodyAt(stop,0)));}l.stops.push(stop);}}
 const metrics=[];for(const c of l.solutions){const s=trace(P.prepareLevel(l),c).state;if(s.status!=='won'||R.collected(l,s)!==3)return null;const pro=trace(P.prepareLevel(l,'pro'),c).state;if(pro.status!=='won'||R.collected(l,pro)!==3)return null;const half=trace(P.prepareLevel(l),c,P.DT/2).state;if(half.status!=='won')return null;const near=[];for(const [da,dv]of offsets){const q={angle:c.angle+da,speed:c.speed+dv};const ss=P.simulate(P.prepareLevel(l),q.angle,q.speed).state;if(ss.status==='won'&&R.collected(l,ss)===3&&(!c.branch||ss.branchId===c.branch))near.push(q);}if(near.length<3)return null;for(let t=1;t<=5;t++){const stats={capture:[25,28,31,34,38,42][t],dockingLevel:t,gravity:[0,52,74,100,132,164][t],gravityMu:[0,3e6,8e6,18e6,35e6,65e6][t]};for(const mode of ['normal','pro']){let st=P.simulate(P.prepareLevel(l,mode),c.angle,c.speed,stats).state;if(st.status!=='won'||R.collected(l,st)!==3)return null;}}metrics.push({...c,time:s.t,loops:s.flybyIndex,portals:s.portalIndex,deliveries:s.dropIndex,precision:s.dockPrecision,proPrecision:pro.dockPrecision,neighbours:near});}
 l.hint=multi?'Посылки принимаются автоматически на пролёте. До портала сначала обслужи адрес текущего участка.':'Сначала выбери направление первой петли; первая телепортация фиксирует ветвь. Переход не меняет скорость.';return{level:l,metrics};}
const fams=(process.argv[2]||'0,1,2,3').split(',').map(Number),all=[];for(const f of fams){const seeds=JSON.parse(fs.readFileSync(path.join(__dirname,`seeds-v8/family-${f}.json`))),used=new Set();for(let i=0;i<4;i++){let done=false;for(let j=0;j<seeds.length;j++){if(used.has(j))continue;const raw=seeds[j];if(f===0&&raw.a.events.length!==(i<2?1:2))continue;if(f===1&&raw.a.events.length!==(i<2?3:4))continue;if(f===2&&raw.a.events.length!==(i===3?5:4))continue;let c=candidate(raw,f,i);if(c){all.push({...c,seed:j});used.add(j);console.log('ACCEPT',c.level.id+1,c.level.name,c.metrics.map(m=>m.neighbours.length));done=true;break;}console.log('reject',f,i,j);}if(!done)throw Error(`No map ${f}/${i}`);}}
fs.writeFileSync(path.join(root,`docs/authored-v8-${fams.join('-')}.json`),JSON.stringify(all,null,2));
